// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsZDISLISp8nkYLor3fDDl9Gt1HYyGWiw',
    appId: '1:711479459330:web:ff37b107302558fc07711b',
    messagingSenderId: '711479459330',
    projectId: 'spotify-clone-25ed1',
    authDomain: 'spotify-clone-25ed1.firebaseapp.com',
    databaseURL: 'https://spotify-clone-25ed1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify-clone-25ed1.appspot.com',
    measurementId: 'G-F3C19K02R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1q3VHmJP7_9MgLDcXltnptqecN_zmbHM',
    appId: '1:711479459330:android:3ea3dd6bcc1beebc07711b',
    messagingSenderId: '711479459330',
    projectId: 'spotify-clone-25ed1',
    databaseURL: 'https://spotify-clone-25ed1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify-clone-25ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJKhqYlWXw5GmfQVEQZDJnkKeVl1uMBR0',
    appId: '1:711479459330:ios:52fcc5ad989e2d0a07711b',
    messagingSenderId: '711479459330',
    projectId: 'spotify-clone-25ed1',
    databaseURL: 'https://spotify-clone-25ed1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify-clone-25ed1.appspot.com',
    androidClientId: '711479459330-j6cknhmsr7prql4vhglh8b8egggieoo5.apps.googleusercontent.com',
    iosClientId: '711479459330-h0549jioud669ncejo0o91qkitl5tevi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJKhqYlWXw5GmfQVEQZDJnkKeVl1uMBR0',
    appId: '1:711479459330:ios:52fcc5ad989e2d0a07711b',
    messagingSenderId: '711479459330',
    projectId: 'spotify-clone-25ed1',
    databaseURL: 'https://spotify-clone-25ed1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify-clone-25ed1.appspot.com',
    androidClientId: '711479459330-j6cknhmsr7prql4vhglh8b8egggieoo5.apps.googleusercontent.com',
    iosClientId: '711479459330-h0549jioud669ncejo0o91qkitl5tevi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );
}
